### ISSUE TITLE
Turkish Support please

### ISSUE THREAD

**Issue by Medullitus** [abuibrahim2/quranlookup#25]
Can you add Turkish please? Thx

**Comment by CrashPilotQA** [comment]
What do you need?

**Comment by abuibrahim2** [comment]
That is now available in the latest version.

In the settings you go to:
Settings
- Make sure "Include Translations" is toggled on
- Choose "Translator Language" as "TR"
- You'll be able to choose from 1 of the 3 translators present

![image](https://github.com/user-attachments/assets/00cb699f-6c05-4d91-9e6d-5c2dd4cf5abb)
